version = 1

test_patterns = ["test/**"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["/"]

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "11"

[[transformers]]
name = "google-java-format"
enabled = true